openapi: 3.0.0
info:
  title: week 9
  version: 1.0.0
servers:
  - url: http://localhost:5000
tags:
  - name: auth
  - name: movies
  - name: users

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/auth/register:
    post:
      tags:
        - auth
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {
                "email": "string",
                "password": "string",
                "confirmPassword": "string",
                "gender": "Female | Male",
                "role": "string"
              }

      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: {
                  "success": true,
                  "message": "User created successfully",
                  "data": {
                    "user": {
                        "id": 1,
                        "email": "test@gmail.com",
                        "gender": "Male",
                        "password": "passwordHashed",
                        "role": "Engineer"
                    }
                  }
                }
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                example: {
                  "success": false,
                  "message": "error message",
                  "type": "ERROR_TYPE"
                }

  /api/auth/login:
    post:
      tags:
        - auth
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {
                "email": "string",
                "password": "string"
              }

      responses:
        '200':
          description: Successful response
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": true,
                  "message": "Login success",
                  "data": {
                    "accessToken": "Bearer token"
                  }
                }
              }
            }
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                example: {
                  "success": false,
                  "message": "error message",
                  "type": "ERROR_TYPE"
                }
        '401':
          description: Unauthorized
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": false,
                  "message": "You are not authenticated",
                  "type": "AUTHENTICATION_ERR"
                }
              }
            }

  /api/movies:
    get:
      tags:
        - movies
      summary: Get all movies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": true,
                  "message": "Get movies success",
                  "data": {
                    "pagination": {
                      "totalPage": 10,
                      "nextPage": 4,
                      "prevPage": 2,
                      "currentPage": 3,
                      "limit": 10
                    },
                    "movies": [
                      {
                        "id": 21,
                        "title": "To Be or Not to Be",
                        "genres": "Comedy|Drama|War",
                        "year": "2011"
                      }
                    ]
                  }
                }
              }
            }
        '401':
          description: Unauthorized
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": false,
                  "message": "You are not authenticated",
                  "type": "AUTHENTICATION_ERR"
                }
              }
            }

  /api/users:
    get:
      tags:
        - users
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": true,
                  "message": "Get movies success",
                  "data": {
                    "pagination": {
                      "totalPage": 10,
                      "nextPage": 2,
                      "prevPage": null,
                      "currentPage": 1,
                      "limit": 10
                    },
                    "movies": [
                      {
                        "id": 1,
                        "email": "oainger0@craigslist.org",
                        "gender": "Female",
                        "role": "Construction Worker"
                      },
                    ]
                  }
                }
              }
            }
        '401':
          description: Unauthorized
          content:
            application/json: {
              schema: {
                type: object,
                example: {
                  "success": false,
                  "message": "You are not authenticated",
                  "type": "AUTHENTICATION_ERR"
                }
              }
            }